apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dt-github-pr-merged-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-pull-request
      eventSourceName: dt
      eventName: pull_request
      filters:
        data:
          - path: body.action
            type: string
            value:
              - closed
          - path: pull_request.merged
            type: bool
            value:
              - "true"
  triggers:
    - template:
        name: github-pr-closed-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: release-
                namespace: argo
              spec:
                serviceAccountName: workflow
                podGC:
                  strategy: OnWorkflowCompletion
                  deleteDelayDuration: 30m
                workflowTemplateRef:
                  name: ci-devops-app-release
                arguments:
                  parameters:
                    - name: pr_number
                      value: ""
                    - name: pr_title
                      value: ""
                    - name: pr_url
                      value: ""
                    - name: pr_user
                      value: ""
                    - name: sha
                      value: ""
                    - name: short_sha
                      value: ""
                    - name: branch
                      value: ""
                    - name: target_branch
                      value: ""
                    - name: app_repo
                      value: ""
                    - name: organization
                      value: ""
                    - name: github_user_name
                      value: ""
                    - name: github_user_email
                      value: ""
          parameters:
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.number
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.title
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.html_url
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.user.login
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.head.sha
              dest: spec.arguments.parameters.4.value
            - src:
                dependencyName: github-pull-request
                dataTemplate: '{{ .Input.body.pull_request.head.sha | substr 0 7 }}'
              dest: spec.arguments.parameters.5.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.head.ref
              dest: spec.arguments.parameters.6.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.base.ref
              dest: spec.arguments.parameters.7.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.repository.name
              dest: spec.arguments.parameters.8.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.repository.owner.login
              dest: spec.arguments.parameters.9.value
            - src:
                dependencyName: github-pull-request
                dataKey: body.repository.owner.login
              dest: spec.arguments.parameters.10.value
            - src:
                dependencyName: github-pull-request
                dataTemplate: 'release-{{ .Input.body.pull_request.number }}-{{ .Input.body.repository.name}}-{{ .Input.body.pull_request.head.sha | substr 0 7 }}'
              dest: metadata.name
              operation: append
