apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.35
  template:
    metadata:
      name: '{{cluster}}-ingress-nginx'
    spec:
      project: core
      destination:
        namespace: ingress-nginx
        server: '{{url}}'
      sources:
        - repoURL: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          targetRevision: 4.*.*
          helm:
            releaseName: ingress-nginx
            valueFiles:
              - $values/values/{{cluster}}/ingress-nginx/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true
