apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        revision: v0.2.0-alpha.19
  template:
    metadata:
      name: '{{cluster}}-kube-prometheus-stack'
    spec:
      project: monitoring
      destination:
        namespace: monitoring
        server: '{{url}}'
      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 65.*.*
          helm:
            releaseName: prometheus
            valueFiles:
              - $values/values/{{cluster}}/kube-prometheus-stack/values.yaml
        - repoURL: git@github.com:devops-toys/devops-app.git
          targetRevision: '{{revision}}'
          ref: values
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=false
          - FailOnSharedResource=true
          - RespectIgnoreDifferences=true
          - PruneLast=true

